version: "3.8"
services:
  lfs:
    image: h3rmt/localfilesharing
    restart: always
    ports:
      - "8080:80"
    environment:
      - ADMIN_PASSWORD=testtest
      - ADMIN_EMAIL=admin@example.com
      - USER_PASSWORD=test
    volumes:
      - ./pb_data:/app/pb_data
