version: "3.8"
services:
  localfilesharing:
    # image: h3rmt/localfilesharing
    build: .
    restart: always
    ports:
      - "8080:80"
    environment:
      - HOST=0.0.0.0
      - PORT=80
      - ADMIN_PASSWORD=testtest
      - ADMIN_EMAIL=admin@example.com
      - USER_PASSWORD=test
    volumes:
      - ./pb_data:/app/pb_data
