version: '3.8'
services:
  db:
    image: .
    restart: always
    environment:
      - PUBLIC_HOST=localhost:8080
    ports:
      - '8080:8080'
    volumes: 
      - ./pb_data:/pb_data

volumes:
  pb_data: